

# ?? ??
server:
  port: 9005

# spring ??
spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: cafeService

# Eureka ??
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

# config ??
mybatis:
  config-location: classpath:config/myBatis.xml